# Generated by Django 5.2 on 2025-04-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstoreapp', '0002_pet_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='petimage',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
